[project]
name = "email-reminder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "brevo-python>=1.1.2",
    "python-dotenv>=1.1.0",
    "scheduler>=0.8.8",
    "xata>=1.3.5",
]
